<?php

global $APPLICATION;

$data = json_decode($_POST['data'], true);
$options = json_decode($_POST['options'], true);
$tableData = json_decode($_POST['tableData'], true);

$header = $tableData['header'];
$body = $tableData['body'];

$control = $APPLICATION->FUNCTIONS->{$options['control']};

$RECORDS = $control->filterTableRecord($data);
//
$ID = $options['id'];
////
////?>
<?= CreateTable(array_map(function($r) {
    return $r == "ID" ? "NO" : $r;
}, $header), array_map(function($r) {
    return $r == "id" ? "no" : $r;
}, $body), $RECORDS, $ID) ?>


