<?php
global  $APPLICATION, $LOAN_ITEM_TABLE_HEADER_TEXT, $LOAN_ITEM_TABLE_BODY_KEY;

$data = $_POST['id'];
$control = $APPLICATION->FUNCTIONS->LOAN_CONTROL;
$RECORDS = $control->filterRecords(['employee_id' => $data],false);
$ID = "loan_id";

$table = CreateTable($LOAN_ITEM_TABLE_HEADER_TEXT, $LOAN_ITEM_TABLE_BODY_KEY, $RECORDS, $ID, false, true, true, true, false);

echo  json_encode([
    "table" => $table,
    "total" => array_sum(array_map(function ($record) {
        return $record['balance'];
    }, $RECORDS))
]);
