<?php

?>
<div class="right-header">
    <div class="flex-container">
        <div class="left">
            <!-- <div class="text-image">
                <?= UseIcon("building-thin") ?>
            </div> -->
            <div class="text-logo">
                <h2>Human Resources Information System</h2>
            </div>
        </div>
        <div class="right">

            <div class="buttons">
                <div class="nav-button notif has-notifications">
                    <div class="icon main">
                        <?= UseIcon("bell-thin") ?>
                    </div>
                </div>

                <div class="nav-button profile">
                    <div class="icon main">
                        <?= UseIcon("caret-down-thin") ?>
                    </div>
                    <div class="content"></div>
                </div>
            </div>
        </div>
    </div>
</div>