<?php
global $APPLICATION;
use Application\models\Client;
use Application\models\PayslipRates;
use Application\models\ServiceDeduction;

$mainData = json_decode($_POST['data'], true);
$control = $APPLICATION->FUNCTIONS->DISBURSEMENT_CONTROL;
$ids = $mainData['ids'];

$records = array_map(function ($id) use ($control) {
    return $control->get($id, true);
}, $ids);

function CreateDisbursementPage($disbursement)
{
    global $APPLICATION;
    global $REQUISITION_REPORT_TABLE_HEADER_TEXT, $REQUISITION_REPORT_LESS_TABLE_BODY_KEY;

    $bankControl = $APPLICATION->FUNCTIONS->BANK_CONTROL;
    $requsition = $disbursement->requisition;

    $RECORDS = array_map(function ($record) {
        $record = (array) $record;

        $record['total_less'] = 0;

        if ($record['requisition_type'] == 1) {
            $record['particulars'] = 'Less; ' . $record['particulars'];
            $record['total_less'] = $record['amount'];
            $record['amount'] = '';
        }

        return $record;
    }, $requsition->requisition_info);

    usort($RECORDS, function ($a, $b) {
        return strcmp($a['requisition_type'], $b['requisition_type']);
    });

    $ID = "requisition_id";
    $BUTTON = -1;

    $output = '
        <div class="print-preview-container">
            <div class="print-preview-header">
                <h2>CDM SECURITY AGENCY, INC.</h2>
                <p>Salusoy, Meycauayan City, Bulacan, (044) 840-8145</p>

                <div class="title-parent">
                <div class="title-container-fill">
                    <h3 class="title">PETTY CASH VOUCHER</h3>
                </div>
</div>
            </div>
            <div class="print-preview-sub-body">
                <div class="main-left">
                    <div class="text">
                        <div class="left">
                            <p>DATE: </p>
                        </div>
                        <div class="right">
                            <span>'. $disbursement->date .'</span>
                        </div>
                    </div>
                    <div class="text">
                        <div class="left">
                            <p>PAID TO: </p>
                        </div>
                        <div class="right">
                            <b>' . $disbursement->paid_to .'</b>
                        </div>
                    </div>
                </div>
                <div class="main-right">
                    <div class="all-text">
                        <b>'. $disbursement->voucher .'</b>
                        <p>'. $disbursement->payments .'</p>
                    </div>
                </div>
            </div>
            <div class="print-preview-body">
                '.
                CreateTable($REQUISITION_REPORT_TABLE_HEADER_TEXT, $REQUISITION_REPORT_LESS_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON, true, true, true, true, [], true)
                .'
            </div> 
            <div class="print-preview-footer">
                <div class="footer-left">
                    <p>AMOUNT IN WORDS: <b>'. strtoupper(NumberToWords($disbursement->amount)) .' PESOS ONLY</b></p>
                </div>
                <div class="footer-right">
                    <div class="sub-total-container">
                        <p>₱'. number_format($requsition->total_expenses) .'</p>
                    </div>
                    <div class="total-container">
                        <div class="t-l">
                            <p>TOTAL</p>
                        </div>
                        <div class="t-r">
                            <p>₱'. number_format($disbursement->amount) .'</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="print-preview-extra">';

            if ($disbursement->payments !== "CASH") {
                $bank = $bankControl->get($disbursement->bank_id, true);

                $output .='
                <div class="payment-information-parent">
                    <div class="payment-information">
                        ';

                if ($disbursement->payments === "CHEQUE") {
                    $output .= '
                <div class="item">
                    <div class="l"><b>CHEQUE #:</b></div>
                    <div class="r"><span>'. $disbursement->cheque_number .'</span></div>
                </div>
                <div class="item">
                    <div class="l"><b>CHEQUE DATE:</b></div>
                    <div class="r"><span>'. $disbursement->cheque_date .'</span></div>
                </div>
                ';
                }

                $output   .= '
                <div class="item">
                    <div class="l"><b>BANK:</b></div>
                    <div class="r"><span>'. $bank->name .'</span></div>
                </div>
                <div class="item">
                    <div class="l"><b>BRANCH:</b></div>
                    <div class="r"><span>'. $bank->branch .'</span></div>
                </div>

                    </div>
                </div>';
            } else {
                $output .='<div></div>';
            }


    $output .='
                <div class="signature-containers">
                    <div class="singature-container">
                         <div class="line"></div>
                        <p>ADMINISTRATOR</p>
                        <p>Approved by</p>
                    </div>  
                    <div class="singature-container">
                         <div class="line"></div>
                        <p>'. $disbursement->paid_to .'</p>
                        <p>Received by</p>
                    </div>    
                </div>
            </div>
        </div>
    ';

    return $output;
}

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table max-height">
            <div class="popup-top">
                <div class="headline">
                    <h1>Preview Print</h1>
                </div>
                <div class="paragraph">
                    <p>Print Disbursements</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="print-preview-containers">
                        <?php foreach ($records as $record): ?>
                            <?= CreateDisbursementPage($record) ?>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="main-table-body main-table-requests">

                    </div>
                </div>

                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Print">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>