<?php
global $APPLICATION;
global $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT;

use Application\models\Requisition;


$data = json_decode($_POST['data'], true);
$id = $data['id'];
$control = $APPLICATION->FUNCTIONS->REQUISITION_CONTROL;
$requisitioninfoControl= $APPLICATION->FUNCTIONS->REQUISITION_INFO_CONTROL;

/**
 * @type Requisition
 */
$requisition = $control->get($id, true);

$RECORDS = $requisitioninfoControl->filterRecords(['requisition_id' => $requisition->requisition_id], false);
$EXPENSES_RECORDS = array_filter($RECORDS,function ($record) {
    return $record['requisition_type'] == 0;
});
$LESS_RECORDS = array_filter($RECORDS, function ($record) {
    return $record['requisition_type'] == 1;
});;
$ID = "requisition_info_id";
$BUTTON = -1;

$FINALIZED = $requisition->status == RequisitionStatusType::FINALIZED->value;

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Requisition</h1>
                </div>
                <div class="paragraph">
                    <p>List of Requisition</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Remarks</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="remarks" placeholder="Remarks" value="<?=$requisition->remarks?>" disabled="<?= $FINALIZED ?>">
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Status</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="status" placeholder="Status" value="<?=$requisition->status?>" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="tab-container-picker table-requisition-picker"  data-id="requisition-picker">
                        <div class="tab-header">
                            <div class="tab-button side-bar-button" data-id="expenses" data-picker="requisition-picker">
                                <div class="text">
                                    <span>
                                        EXPENSES
                                    </span>
                                </div>
                            </div>
                            <div class="tab-button side-bar-button" data-id="less" data-picker="requisition-picker">
                                <div class="text">
                                    <span>
                                        LESS
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="tab-body">
                            <div class="tab-content side-bar-content expenses-content" data-content="expenses" data-picker="requisition-picker">
                                <div class="data-table-content">
                                    <div class="main-table-container table-component full">
                                        <div class="main-table-header">
                                            <div class="table-header">
                                                <div class="left">
                                                    <div class="title">
                                                        <h2>Expenses</h2>
                                                    </div>
                                                </div>
                                                <div class="center"></div>
                                                <div class="right"></div>
                                            </div>
                                            <div class="table-buttons">
                                                <?php if (!$FINALIZED): ?>
                                                <div class="left"></div>
                                                <div class="right">
                                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                                        <div class="icon">
                                                            <?= UseIcon("trash-thin") ?>
                                                        </div>
                                                    </div>

                                                    <div class="icon-button table-button show-component" data-name="add-request">
                                                        <div class="icon">
                                                            <?= UseIcon("plus-thin") ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php endif ?>
                                            </div>
                                        </div>
                                        <div class="main-table-body main-table-requests">
                                            <?= CreateTable($REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT, $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $EXPENSES_RECORDS, $ID, $BUTTON, $FINALIZED) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-content side-bar-content less-content" data-content="less" data-picker="requisition-picker">
                                <div class="data-table-content">
                                    <div class="main-table-container table-component full">
                                        <div class="main-table-header">
                                            <div class="table-header">
                                                <div class="left">
                                                    <div class="title">
                                                        <h2>Less</h2>
                                                    </div>
                                                </div>
                                                <div class="center"></div>
                                                <div class="right"></div>
                                            </div>
                                            <div class="table-buttons">
                                                <?php if (!$FINALIZED): ?>

                                                <div class="left"></div>
                                                <div class="right">
                                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                                        <div class="icon">
                                                            <?= UseIcon("trash-thin") ?>
                                                        </div>
                                                    </div>

                                                    <div class="icon-button table-button show-component" data-name="add-request">
                                                        <div class="icon">
                                                            <?= UseIcon("plus-thin") ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php endif ?>

                                            </div>
                                        </div>
                                        <div class="main-table-body main-table-requests">
                                                <?= CreateTable($REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT, $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $LESS_RECORDS, $ID, $BUTTON, $FINALIZED) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <?php if(!$FINALIZED): ?>
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                                <input type="submit" value="Save">
                        </div>
                    </div>
                    <?php endif ?>

                </div>
            </form>
        </div>
    </div>
</div>