<?php
global $APPLICATION;

$control = $APPLICATION->FUNCTIONS->SYSTEM_TYPES_CONTROL;
$LOAN_TYPES = $control->filterRecords(['category' => 'loan_type'], false);

$TYPES = ObjectToCombo("type", "type_id", $LOAN_TYPES);

$INTEREST_RATES = [];
for ($i = 0; $i <= 100; $i++) {
    $INTEREST_RATES[] = ["value" => (string)$i, "text" => $i . "%"];
}

$PAYABLE_BY = [];
for ($i = 1; $i <= 24; $i++) {
    $PAYABLE_BY[] = ["value" => (string)$i, "text" => $i . " Times"];
}

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Payment Option</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Principal Amount</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="principal" placeholder="Principal Amount" step=".01" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Payable By</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("payable_by", "Payable By", $PAYABLE_BY) ?>
                            </div>
                        </div>
                    </div> 

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Interest Rate</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("interest_rate", "Interest Rate", $INTEREST_RATES) ?>
                            </div>
                        </div>
                    </div> 

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Interest Value</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="interest_value" placeholder="Interest Value" step=".01" readonly>
                            </div>
                        </div>
                    </div> 

                    <div class="payment-statement-preview">
                        <div class="preview-title">
                            <h3>Payment Statement</h3>
                        </div>
                        <div class="preview-content">
                            
                        </div>
                    </div>

                                     
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="text-button back-button">
                                <div class="text">
                                    <span>Back</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Add Loan">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>